-- 01_create_schema.sql
CREATE OR REPLACE DATABASE CS5542_WEEK5;
CREATE OR REPLACE SCHEMA CS5542_WEEK5.PUBLIC;

-- Example "project subset" tables
CREATE OR REPLACE TABLE CS5542_WEEK5.PUBLIC.EVENTS (
  EVENT_ID STRING,
  EVENT_TIME TIMESTAMP_NTZ,
  TEAM STRING,
  CATEGORY STRING,
  VALUE FLOAT
);

CREATE OR REPLACE TABLE CS5542_WEEK5.PUBLIC.USERS (
  USER_ID STRING,
  TEAM STRING,
  ROLE STRING,
  CREATED_AT TIMESTAMP_NTZ
);
