-- 02_stage_and_load.sql

-- Warehouse
CREATE OR REPLACE WAREHOUSE COMPUTE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE WAREHOUSE COMPUTE_WH;
USE DATABASE CS5542_WEEK5;
USE SCHEMA PUBLIC;

-- File format for CSV
CREATE OR REPLACE FILE FORMAT CS5542_CSV_FMT
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null');

-- Stage (internal)
CREATE OR REPLACE STAGE CS5542_STAGE
  FILE_FORMAT = CS5542_CSV_FMT;

-- After a file is uploaded to @CS5542_STAGE (e.g., events.csv), load it:
-- COPY INTO EVENTS
-- FROM @CS5542_STAGE/events.csv
-- ON_ERROR = 'CONTINUE';
