-- 03_queries.sql
USE DATABASE CS5542_WEEK5;
USE SCHEMA PUBLIC;

-- Q1: basic aggregation
SELECT TEAM, CATEGORY, COUNT(*) AS N, AVG(VALUE) AS AVG_VALUE
FROM EVENTS
GROUP BY TEAM, CATEGORY
ORDER BY N DESC;

-- Q2: time filter + top-k
SELECT CATEGORY, COUNT(*) AS N_24H
FROM EVENTS
WHERE EVENT_TIME >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
GROUP BY CATEGORY
ORDER BY N_24H DESC
LIMIT 10;

-- Q3: join across tables (who is producing what categories)
SELECT U.TEAM, U.ROLE, E.CATEGORY, COUNT(*) AS N
FROM USERS U
JOIN EVENTS E
  ON U.TEAM = E.TEAM
GROUP BY U.TEAM, U.ROLE, E.CATEGORY
ORDER BY N DESC;
