-- 03_queries.sql
-- Multi-Agent AI Attack Swarm Detection — Analytics Queries
USE DATABASE CS5542_WEEK5;
USE SCHEMA PUBLIC;

-- Q1: Session distribution by attacker type and source
SELECT LABEL, SOURCE, COUNT(*) AS SESSION_COUNT, AVG(COMMAND_COUNT) AS AVG_COMMANDS
FROM SESSIONS
GROUP BY LABEL, SOURCE
ORDER BY SESSION_COUNT DESC;

-- Q2: Behavioral fingerprinting — latency statistics per attacker type
-- (AI swarms show uniform low latency; humans show high variance)
SELECT
  S.LABEL,
  COUNT(DISTINCT S.SESSION_ID) AS SESSIONS,
  COUNT(C.COMMAND) AS TOTAL_COMMANDS,
  ROUND(AVG(C.LATENCY), 3) AS AVG_LATENCY,
  ROUND(STDDEV(C.LATENCY), 3) AS STD_LATENCY,
  ROUND(MIN(C.LATENCY), 3) AS MIN_LATENCY,
  ROUND(MAX(C.LATENCY), 3) AS MAX_LATENCY
FROM SESSIONS S
JOIN COMMANDS C ON S.SESSION_ID = C.SESSION_ID
GROUP BY S.LABEL
ORDER BY AVG_LATENCY;

-- Q3: Top 20 most common commands per attacker type
-- (reveals attack patterns: swarms run recon, bots run nmap/hydra)
SELECT LABEL, COMMAND, CMD_COUNT
FROM (
  SELECT
    S.LABEL,
    C.COMMAND,
    COUNT(*) AS CMD_COUNT,
    ROW_NUMBER() OVER (PARTITION BY S.LABEL ORDER BY COUNT(*) DESC) AS RN
  FROM SESSIONS S
  JOIN COMMANDS C ON S.SESSION_ID = C.SESSION_ID
  GROUP BY S.LABEL, C.COMMAND
)
WHERE RN <= 20
ORDER BY LABEL, CMD_COUNT DESC;
